create table public.rundown (
    id bigint generated by default as identity not null,
    nama character varying null,
    jam_mulai time without time zone null,
    jam_selesai time without time zone null,
    tanggal_id bigint null,
    created_at timestamp with time zone not null default now(),
    link_gmaps character varying null,
    rating double precision null,
    constraint rundown_pkey primary key (id),
    constraint rundown_tanggal_id_fkey foreign KEY (tanggal_id) references tanggal (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.error (
    id bigint generated by default as identity not null,
    nama character varying null,
    jam_mulai time without time zone null,
    jam_selesai time without time zone null,
    error_detail character varying null,
    tanggal_id bigint null,
    created_at timestamp with time zone not null default now(),
    constraint error_pkey primary key (id),
    constraint error_tanggal_id_fkey foreign KEY (tanggal_id) references tanggal (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.tanggal (
    id bigint generated by default as identity not null,
    tanggal date null,
    status character varying null,
    created_at timestamp with time zone not null default now(),
    constraint tanggal_pkey primary key (id)
) TABLESPACE pg_default;